export const exercisesByest = {
  chest: [
    { code: 'CH-B01', description: 'Supino Inclinado' },
    { code: 'CH-H02', description: 'Supino Inclinado com Halteres' },
    { code: 'CH-B03', description: 'Supino com Barra' },
    { code: 'CH-H04', description: 'Supino com Halteres' },
    { code: 'CH-C05', description: 'Crossover' },
    { code: 'CH-F06', description: 'Flexões em Inclinação' },
    { code: 'CH-F07', description: 'Flexões em Declinação' },
    { code: 'CH-F08', description: 'Flexões em Plano' },
    { code: 'CH-H09', description: 'Pullover com Halteres' },
    { code: 'CH-H10', description: 'Fly Reto' },
    { code: 'CH-H11', description: 'Fly Inclinado' },
    { code: 'CH-M12', description: 'Peitoral na Máquina' },
    { code: 'CH-H13', description: 'Supino Declinado com Halteres' },
  ],
  shoulders: [
    { code: 'SH-H01', description: 'Desenvolvimento com Halteres' },
    { code: 'SH-H02', description: 'Desenvolvimento em Pé com Halteres' },
    { code: 'SH-H03', description: 'Elevações Laterais' },
    { code: 'SH-H04', description: 'Elevações Frontais' },
    { code: 'SH-B05', description: 'Press Militar' },
    { code: 'SH-B06', description: 'Remada Alta' },
    { code: 'SH-B07', description: 'Puxada com Barra para o queixo' },
  ],
  biceps: [
    { code: 'BI-B01', description: 'Rosca Direta com Barra' },
    { code: 'BI-H02', description: 'Rosca Direta com Halteres' },
    { code: 'BI-H03', description: 'Rosca Concentrada' },
    { code: 'BI-M04', description: 'Rosca Scott' },
    { code: 'BI-H05', description: 'Rosca Martelo' },
    { code: 'BI-H06', description: 'Rosca Alternada' },
    { code: 'BI-B07', description: 'Rosca Inversa com Barra' },
    { code: 'BI-H08', description: 'Rosca Zottman' },
    { code: 'BI-C09', description: 'Rosca no Cabo' },
    { code: 'BI-C10', description: 'Rosca no Cabo Inclinada' },
  ],
  triceps: [
    { code: 'TR-C01', description: 'Pulley com Barra' },
    { code: 'TR-C02', description: 'Pulley com Corda' },
    { code: 'TR-B03', description: 'Tríceps Testa com Barra' },
    { code: 'TR-H04', description: 'Tríceps Francês com Halteres' },
    { code: 'TR-B05', description: 'Tríceps com Barra no Banco' },
    { code: 'TR-B06', description: 'Tríceps Francês com Barra' },
    { code: 'TR-C07', description: 'Tríceps Pulley Unilateral' },
    { code: 'TR-F08', description: 'Fundos no Banco' },
    { code: 'TR-F09', description: 'Tríceps Mergulho na Paralela' },
    { code: 'TR-C10', description: 'Pulley com Pegada Reversa' },
  ],
  quadriceps: [
    { code: 'QU-M05', description: 'Extensão de Pernas' },
    { code: 'QU-B01', description: 'Agachamento Livre' },
    { code: 'QU-H02', description: 'Agachamento com Halteres' },
    { code: 'QU-M03', description: 'Leg Press 45' },
    { code: 'QU-M04', description: 'Leg Press Horizontal' },
    { code: 'QU-M06', description: 'Hack Squat' },
    { code: 'QU-H14', description: 'Sumô com Halteres' },
    { code: 'QU-M13', description: 'Máquina Adutora' },
    { code: 'QU-B24', description: 'Agachamento Sumô com Barra' },
    { code: 'QU-H17', description: 'Agachamento Sumô com Halteres' },
  ],
  posterior: [
    { code: 'PO-M07', description: 'Flexor de Pernas Sentado' },
    { code: 'PO-M08', description: 'Flexor de Pernas deitado' },
    { code: 'PO-B09', description: 'Stiff (Levantamento Terra Romeno)' },
  ],
  gluteal: [
    { code: 'GL-M10', description: 'Glúteo na Máquina' },
    { code: 'GL-M12', description: 'Levantamento com Polia Frontal' },
    { code: 'GL-M20', description: 'Glúteo no Smith' },
    { code: 'GL-B21', description: 'Elevação pélvica com Barra' },
    { code: 'GL-M22', description: 'Elevação pélvica na máquina' },
    { code: 'GL-M23', description: 'Extensão de Quadril na Máquina' },
    { code: 'GL-C24', description: 'Kickback no Cabo' },
    { code: 'GL-M11', description: 'Máquina Abdutora' },
    { code: 'GL-B22', description: 'Levantamento Terra com Barra' },
    { code: 'GL-B23', description: 'Levantamento Terra Sumô com Barra' },
  ],
  calf: [
    { code: 'CA-M15', description: 'Panturrilha no Smith' },
    { code: 'CA-H16', description: 'Elevação de Panturrilha com Halteres' },
    { code: 'CA-M17', description: 'Panturrilha em Pé na Máquina' },
    { code: 'CA-M18', description: 'Panturrilha no Leg Press' },
    { code: 'CA-M19', description: 'Panturrilha Sentado no Smith' },
  ],
  back: [
    { code: 'BK-B01', description: 'Puxada Alta na Barra' },
    { code: 'BK-C02', description: 'Puxada com Corda' },
    { code: 'BK-B03', description: 'Puxada Frontal' },
    { code: 'BK-M04', description: 'Puxada na Horizontal' },
    { code: 'BK-H05', description: 'Remada com Halteres' },
    { code: 'BK-B06', description: 'Remada Curvada com Barra' },
    { code: 'BK-B07', description: 'Remada T-Bar' },
    { code: 'BK-M08', description: 'Remada Cavalinho' },
    { code: 'BK-M09', description: 'Tração no Lat Pulldown' },
    { code: 'BK-H10', description: 'Remada Baixa com Halteres' },
    { code: 'BK-B11', description: 'Pulldown com Pegada Pronada' },
    { code: 'BK-B12', description: 'Pulldown com Pegada Fechada' },
    { code: 'BK-B13', description: 'Levantamento Terra com Barra' },
    { code: 'BK-H14', description: 'Levantamento Terra com Halteres' },
    { code: 'BK-M15', description: 'Pull-Over no Smith' },
    { code: 'BK-F16', description: 'Hiperextensão Lombar' },
  ],
  abs: [
    { code: 'AB-F01', description: 'Abdominal Supra' },
    { code: 'AB-F02', description: 'Abdominal Infra' },
    { code: 'AB-M03', description: 'Máquina Abdominal' },
    { code: 'AB-C04', description: 'Elevação de Pernas no Cabo' },
    { code: 'AB-F05', description: 'Prancha Abdominal' },
    { code: 'AB-F06', description: 'Abdominal Oblíquo' },
    { code: 'AB-C07', description: 'Twist no Cabo' },
    { code: 'AB-F08', description: 'Crunch' },
    { code: 'AB-F22', description: 'Hiperextensão Lombar' },
  ],
};
